#!/bin/bash

# check if counter user exists
if ! id -u counter >/dev/null 2>&1; then
	echo "Creating counter user"
	sudo adduser --system counter
fi

# Starting service
echo "Enabling service.."
sudo systemctl daemon-reload
sudo systemctl enable counter.service
sudo systemctl start counter.service
